name: hp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ase=3.22.1=pyhd8ed1ab_1
  - biopython=1.81=py39h72bdee0_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.4=h0f2a231_0
  - boost=1.78.0=py39h7c9e3ff_4
  - boost-cpp=1.78.0=h6582d0a_3
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py39h5a03fae_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cairo=1.16.0=hf32fb01_1
  - cclib=1.7.2=pyhd8ed1ab_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - contourpy=1.1.0=py39h7633fee_0
  - curl=8.1.1=h5eee18b_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - f90wrap=0.2.13=py39h9cbb48f_0
  - fftw=3.3.10=nompi_hc118613_108
  - flask=2.3.2=pyhd8ed1ab_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.40.0=py39hd1e30aa_0
  - freetype=2.12.1=hca18f0e_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gawk=5.1.0=h7f98852_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - greenlet=2.0.2=py39h3d6467e_1
  - gsl=2.7=he838d99_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.0=nompi_h5231ba7_103
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kim-api=2.3.0=h94b5c5c_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.20.1=hf9c8cef_0
  - lammps=2023.03.28=py39hb96d42f_openmpi_2
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=17_linux64_openblas
  - libcurl=8.1.1=h91b91d3_1
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.68.4=h3e27bee_0
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnetcdf=4.9.2=nompi_h0f3d0bb_105
  - libnghttp2=1.52.0=ha637b67_1
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.1=h8b53f26_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.4=h0d562d8_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.3=py39hd1e30aa_0
  - matplotlib-base=3.7.1=py39he190548_0
  - mlip=1.0=hbfab9f8_2
  - mpi=1.0=openmpi
  - munkres=1.1.4=pyh9f0ad1d_0
  - n2p2=2.2.0=py39h0df3ca5_3
  - ncurses=6.4=hcb278e6_0
  - numpy=1.23.5=py39h3d75532_0
  - openbabel=3.1.1=py39h421517d_7
  - openjpeg=2.5.0=hfec8fc6_2
  - openmpi=4.1.5=h414af15_101
  - openssl=1.1.1u=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py39h40cae4c_0
  - pcre=8.45=h9c3ff4c_0
  - periodictable=1.5.2=py_0
  - pillow=9.5.0=py39haaeba84_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - platformdirs=3.8.0=pyhd8ed1ab_0
  - plumed=2.9.0=nompi_h752ec8b_100
  - pooch=1.7.0=pyha770c72_3
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.24.0=py39hc92de75_0
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.0=hffdb5ce_5_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - quippy=0.9.12=py39hba90235_1
  - readline=8.2=h8228510_1
  - reportlab=4.0.4=py39hd1e30aa_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scipy=1.11.1=py39h6183b62_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sqlalchemy=2.0.17=py39hd1e30aa_0
  - sqlite=3.42.0=h2c6b66d_0
  - tk=8.6.12=h27826a3_0
  - typing-extensions=4.7.0=hd8ed1ab_0
  - typing_extensions=4.7.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucx=1.14.1=h0aa22dc_2
  - unicodedata2=15.0.0=py39hb9d737c_0
  - urllib3=2.0.3=pyhd8ed1ab_1
  - voro=0.4.6=h00ab1b0_0
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wget=1.20.3=ha56f1ee_1
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - chemicals==1.1.4
      - fluids==1.0.24
      - psutil==5.9.5
      - rdkit==2023.3.2
      - thermo==0.2.26
      - tqdm==4.65.0
      - dpdata
      - torch
      - torchvision
      - torchaudio
      - torch_geometric
      - networkx
      - matplotlib
      - scikit-learn
prefix: /home/zzy/sw/conda3/envs/hp
